# Generated by Django 5.2.3 on 2025-07-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
