# Generated by Django 5.2.3 on 2025-07-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-код')),
                ('type', models.CharField(choices=[('default', 'Обычная категория (без цены и кол-ва)'), ('with_price_and_sessions', 'С ценой и кол-вом сеансов'), ('with_price_only', 'Только цена, без фото и сеансов')], default='default', max_length=32, verbose_name='Тип отображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='services_ca_id_d6bf2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название услуги/товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('sessions_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сеансов')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии/активно')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/photos/', verbose_name='Фото услуги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='services_se_id_3667db_idx')],
            },
        ),
    ]
