# Generated by Django 5.2.3 on 2025-07-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название варианта услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('session_time', models.DurationField(verbose_name='Время сеанса')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='services.service', verbose_name='Основная услуга')),
            ],
            options={
                'verbose_name': 'Вариант услуги',
                'verbose_name_plural': 'Варианты услуг',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
